### PR TITLE
React hot loader compatibility

### PR DESCRIPTION
**Pull request by connorzg**
See same issue from old repo https://github.com/glittershark/reactable/issues/338

Tables currently won't render currently with react v16+ and RHL

`parseChildData()` compares functions directly, but React hot loader swaps out functions in memory meaning an inequality when determining type. This PR transitions type parsing to function string comparison.

### CODE REVIEW

**Comment by connorzg** [comment]
@abdulrahman-khankan are you an active PR reviewer on this repo? I don't see any default reviewers.

**Comment by abdulrahman-khankan** [comment]
@connorzg thank you for the PR 😃, I am just waiting for the weekend to look at it.

**Review by abdulrahman-khankan — APPROVED** [review]

**Comment by abdulrahman-khankan** [comment]
@connorzg Thank you for the PR. I have merged it, but currently there are problems with publishing to npm (their side). I will upload a new version there as soon as their service is back to normal.

**Comment by abdulrahman-khankan** [comment]
@connorzg it is now available from the npm registry with v1.1.0.

**Comment by connorzg** [comment]
Thanks @abdulrahman-khankan! This resolved the bug and our development process is fixed :)

**Pull request merged**
